#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("drphischel.Resource", IsApplication=true)]

namespace drphischel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			public const int AddPatientBtn = 2131034126;
			
			// aapt resource value: 0x7f050024
			public const int AppointmentBtn = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int LogOutBtn = 2131034149;
			
			// aapt resource value: 0x7f050021
			public const int MedRecordsList = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int MedicAddPatientBtn = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int MedicLogOutBtn = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int MedicViewCalendarBtn = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int MedicViewPatientsBtn = 2131034143;
			
			// aapt resource value: 0x7f05000d
			public const int NewPatientBdateInput = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int NewPatientBdateText = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int NewPatientIdNumberInput = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int NewPatientIdNumberText = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int NewPatientLName1Input = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int NewPatientLName1Text = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int NewPatientLName2Input = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int NewPatientLName2Text = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int NewPatientNameInput = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int NewPatientNameText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int NewPatientPassInput = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int NewPatientPasswordText = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int NewPatientResidenceInput = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int NewPatientResidenceText = 2131034122;
			
			// aapt resource value: 0x7f050016
			public const int PasswordText = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int UserNameText = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int dateDisplay = 2131034127;
			
			// aapt resource value: 0x7f050022
			public const int listView1 = 2131034146;
			
			// aapt resource value: 0x7f05001c
			public const int loginButton = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int loginChoiceText = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int login_choice = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int makeAppointmentBtn = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int medRecordsBtn = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int medic_login = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int patient_login = 2131034138;
			
			// aapt resource value: 0x7f050010
			public const int picDate = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int pickTime = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int timeDisplay = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int userIdInput = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int userPassInput = 2131034135;

			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			public const int AddPatient = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Appointment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Medic = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MedicalRecords = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MedicList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Patient = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ViewCalendar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewPatients = 2130903048;

			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
